import React, { useEffect, useState } from 'react';
import Layout from './components/Layout';import AgentSidebar from './components/AgentSidebar';import AgentCanvas from './components/AgentCanvas';import ConversationPanel from './components/ConversationPanel';import ArtifactPanel from './components/ArtifactPanel';import FileUpload from './components/FileUpload';import ApprovalCard from './components/ApprovalCard';
import { approve, chat, fetchAgents, stream, uploadFiles } from './api/client';

export default function App(){
 const [agents,setAgents]=useState<any[]>([]);const [sessionId,setSessionId]=useState('');const [selected,setSelected]=useState<string[]>([]);const [messages,setMessages]=useState<string[]>([]);const [artifacts,setArtifacts]=useState<any[]>([]);const [status,setStatus]=useState<Record<string,string>>({});const [pending,setPending]=useState<string>();const [input,setInput]=useState('Describe this data and find quality issues');
 useEffect(()=>{fetchAgents().then(setAgents)},[])
 const ensureStream=(sid:string)=>{const es=stream(sid);es.onmessage=(e)=>{const evt=JSON.parse(e.data);if(evt.type==='agent_started')setStatus(s=>({...s,[evt.agent]:'thinking'}));if(evt.type==='agent_message'){setMessages(m=>[...m,`${evt.agent}: ${evt.message}`]);setStatus(s=>({...s,[evt.agent]:'done'}))}if(evt.type==='artifact_generated')setArtifacts(a=>[...a,evt]);if(evt.type==='approval_required'){setPending(evt.pending_action);setMessages(m=>[...m,'Approval required for pipeline generation'])}if(evt.type==='final_response')setMessages(m=>[...m,`Final: ${evt.message}`]);};}
 const onUpload=async(files:File[])=>{const r=await uploadFiles(files,sessionId||undefined);setSessionId(r.session_id);ensureStream(r.session_id);setMessages(m=>[...m,`Uploaded ${r.files.length} files`])}
 const onSend=async()=>{if(!sessionId)return;await chat(sessionId,input,selected);setMessages(m=>[...m,`User: ${input}`])}
 const onApprove=async()=>{if(sessionId&&pending){await approve(sessionId,pending);setPending(undefined)}}
 return <Layout left={<div><div className='p-2 text-xs text-slate-400'>Agents</div><AgentSidebar agents={agents} onSelect={(id)=>setSelected(s=>s.includes(id)?s:[...s,id])}/><div className='p-2 text-xs text-slate-400'>Upload</div><div className='p-2'><FileUpload onUpload={onUpload}/></div></div>} center={<AgentCanvas selected={selected} status={status}/>} right={<div className='h-full flex flex-col'><ApprovalCard pending={pending} onApprove={onApprove}/><ConversationPanel messages={messages}/><ArtifactPanel artifacts={artifacts}/></div>} bottom={<div className='h-full flex items-center gap-2 p-2'><input value={input} onChange={e=>setInput(e.target.value)} className='flex-1 bg-slate-900 border border-slate-700 rounded px-2 py-1 text-sm'/><button onClick={onSend} className='px-3 py-1 bg-cyan-700 rounded text-sm'>Send</button></div>}/>
}
